#!/bin/bash
#
# muutuja kasutamise näide
#
#Defineerime muutuja ja omistame väärtuse
#väärtus saadakse whoami käsust
kasutaja=`whoami`
#valjastame muutuja väärtuse koos seletusega
echo "Tere, $kasutaja!"
#
#loon ja väljastan kella
kell=`date +"%H:%M"`
#
kuupaev=`date +'%d. %B'`
#
echo "Kell on $kell ja kuupäev on $kuupaev."
