#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend:"
	echo "$0 number"
	echo "Näiteks: $0 5"
else
	arv=$1
	#Kui $Arv on suurem kui 1; siis
	if [ $arv -gt 1 ]; then
		#väljasta "$Arv on positiivne"
		echo "Arv $arv on positiivne"
		#Kui ei ole siis Kas $Arv on väiksem kui 0; siis
	elif [ $arv -lt 0 ]; then
		#Väljasta "$Arv on negatiivne"
		echo "Arv $arv on negatiivne"
		#Kui ei ole:
	else
		#Väljasta "$arv on nautraalne"
		echo "$arv on neutraalne"
		#Lõpp
		fi
fi
